### ISSUE TITLE
Text repeating in note

### ISSUE THREAD

**Issue by sarahfg** [Automattic/simplenote-electron#1690]
### Expected
Text should not enter itself.

### Observed
There are 3 recent reports of text repeating in a note. One observed seemingly random text repeating after they began composing, the other 2 observed a phrase they typed being re-entered several times after they finished writing.

We haven't yet gotten details on the versions of Simplenote in use, but it was reported in both Firefox + Chrome.

The user provided this screenshot of the issue https://imgur.com/a/A3Ug0ZL

Reports in:
 - #2468732-zen
 - #2468622-zen
 - #2467831-zen
 - #2466101-zen (resolved after computer-restart)
 - #2463003-zen (waiting for details on versions)
 - #2466039-zen
- #2469859-zen
- #2469966-zen
- #2471800-zen
- #2472233-zen
- #2472424-zen
- #2474263-zen
- #2481525-zen
- #2481965-zen
- #2459341-zen
- #2485841-zen
- #2486134-zen
- #2488756-zen
- #2488826-zen
- #2489177-zen

**Comment by sarahfg** [comment]
There was a similar report at #2466101-zen that was resolved by the user restarting their computer

**Comment by sarahfg** [comment]
Another similar report here #2463003-zen. Trying to get more details on what version they are using

**Comment by sarahfg** [comment]
Another similar at #2466039-zen

**Comment by dmsnell** [comment]
@sarahfg thanks for reporting these. it's sufficient to add the ticket references in the issue summary.

it looks like either we still have that bug out there or (as it looks like a couple people had their issue resolved by flushing cache) that we're dealing with old versions of the web app and should expect that for a few more days.

the Android issue appears like it might be related to having the desktop app open and probably had nothing to do with the Android client. we'll try and keep this up-to-date; thanks for collecting these reports

**Comment by dmsnell** [comment]
I have confirmed that this occurs in Chrome when more than one copy is open. Need to start debugging _why_ it's happening.

**Comment by dmsnell** [comment]
We believe we know why this is happening and why it's present in the web apps: the note database gets shared among the multiple tabs and interferes with itself.

> Shared mutable state is the root of all kinds of evils

🤷‍♂ 

we're going to pursue two options: limit the app to one open browser session, per browser (could be open one in Chrome and one in Safari or one in Firefox, etc…), and work on the underlying library to eliminate this possibility.

in the meantime please let customers know that if they want to have more than one copy of the web app open to do so in different browsers. I realize this isn't a sufficient answer, but it should resolve the immediate issue while allowing them to use multiple copies at once until we have the deeper fix

**Comment by erricgunawan** [comment]
2463003-zen confirmed that using just a single tab works for now.

Thanks for the tips @dmsnell !

**Comment by dmsnell** [comment]
"session-lock" is being implemented in #1700

**Comment by mzorz** [comment]
Just adding another report here 2484216-zen

**Comment by w3sip** [comment]
Has the fix been rolled out already? Just ran into this again, this time with 2nd and 3rd client tabs being open on a different machine -- only one client was open on the machine where the note was being modified.

**Comment by scottsisco** [comment]
This is still affecting me too so it does not seem to be fixed. I am using chrome, but I do not have simplenote open in any other tabs or open on any other computers. In addition to this being a problem for me on the web based version of simplenote. I have also experience the same behavior MacOS simplenote app.

**Comment by dmsnell** [comment]
For those coming here for updates: there's no fix yet - the bug is hiding deeper than we thought. We're going to release a temporary measure to try and limit editing sessions to a single tab which appears to mitigate the bug. We're pursuing this in the meantime to try and eliminate the core problem, which seems to be the result of a concurrency bug with the way that the Simperium library interacts with the client.
